# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18b6c540dd5f08b802286dd0bfe11f06af8bd4660fa33a4794dadb7c2061d3bde138cd292176a1a19fe2a90a06083e286ddcac107c429afaee2a4040a2e95af2

test:
  secret_key_base: d57739ca546a11b66de70b6a863f92a6536e52dc3b30c4308b0326c285fddb016c8fa9f21afeb2db601be5cb4129dee9c422ce2b55815fb9a880d71a83827365

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
